# Surprise 모듈

scikit learn을 활용한 추천 시스템용 패키지

유사도 측정방식의 추천 시스템을 구현

- 순서
  1. 사용자 A가 평점을 준 상품들에 대해 다른 사용자가 준 평점들을 분석
  2. 평점 유사도가 높은 사용자들의 평점 정보를 분석
  3. 사용자 A가 평가를 내리지 않은 상품에 대해 평점 예측

In [1]:
#pip install surprise
import surprise as sp
import pandas as pd

In [2]:
# 사용할 데이터 셋 준비
data = sp.Dataset.load_builtin('ml-100k')
# 정보 데이터(영화ID, 제목)
item_path = 'C:/Users/student/.surprise_data/ml-100k/ml-100k/u.item'
item_list = open(item_path,encoding='iso-8859-2').readlines()

In [3]:
temp_list = []

for line in item_list:
    sd = line.split('|')
    temp_list.append([sd[0], sd[1]])
    
movie_dict = dict(temp_list)
#movie_dict

In [4]:
# 유사도 계산 방식
# 평균 제곱 차이 유사도
option1 = {'name' : 'msd'}
# 코사인 유사도
option2 = {'name' : 'cosine'}
# 피어슨 유사도
option3 = {'name' : 'pearson'}
# 모델 객체를 생성한다
model = sp.KNNBasic(sim_options=option3)
# 학습한다
trainset = data.build_full_trainset()
model.fit(trainset)

Computing the pearson similarity matrix...
Done computing similarity matrix.

In [5]:
# 100번 사용자에 대한 영화 5개를 추천받는다
result = model.get_neighbors(100, k=5)

for r1 in result:
    movie_name = movie_dict.get(str(r1))
    print(movie_name)

Get Shorty (1995)
E.T. the Extra-Terrestrial (1982)
Deer Hunter, The (1978)
My Life as a Dog (Mitt liv som hund) (1985)
Young Poisoner's Handbook, The (1995)

In [6]:
data.raw_ratings
columns = ['user', 'item', 'rate', 'timestemp']
df = pd.DataFrame(data.raw_ratings, columns=columns)
df.iloc[:,0:3]

      user  item  rate
0      196   242   3.0
1      186   302   3.0
2       22   377   1.0
3      244    51   2.0
4      166   346   1.0
5      298   474   4.0
6      115   265   2.0
7      253   465   5.0
8      305   451   3.0
9        6    86   3.0
10      62   257   2.0
11     286  1014   5.0
12     200   222   5.0
13     210    40   3.0
14     224    29   3.0
15     303   785   3.0
16     122   387   5.0
17     194   274   2.0
18     291  1042   4.0
19     234  1184   2.0
20     119   392   4.0
21     167   486   4.0
22     299   144   4.0
23     291   118   2.0
24     308     1   4.0
25      95   546   2.0
26      38    95   5.0
27     102   768   2.0
28      63   277   4.0
29     160   234   5.0
...    ...   ...   ...
99970  449   120   1.0
99971  661   762   2.0
99972  721   874   3.0
99973  821   151   4.0
99974  764   596   3.0
99975  537   443   3.0
99976  618   628   2.0
99977  487   291   3.0
99978  113   975   5.0
99979  943   391   2.0
99980  864   685   4.0
99981  750   323   3.0
99982  279    64   1.0
99983  646   750   3.0
99984  654   370   2.0
99985  617   582   4.0
99986  913   690   3.0
99987  660   229   2.0
99988  421   498   4.0
99989  495  1091   4.0
99990  806   421   4.0
99991  676   538   4.0
99992  721   262   3.0
99993  913   209   2.0
99994  378    78   3.0
99995  880   476   3.0
99996  716   204   5.0
99997  276  1090   1.0
99998   13   225   2.0
99999   12   203   3.0

[100000 rows x 3 columns]